### ISSUE TITLE
modScaleForm & windows 10

### ISSUE THREAD

**Issue by NatxoPi** [GruberMarkus/modScaleForm#1]
![modsacaleformwindows10](https://user-images.githubusercontent.com/34450669/33840061-30742192-de94-11e7-9bf5-7ac1bdca5fbc.JPG)
Hi, I wanted to ask you a question. I use the modScaleForm in an application that worked under Office 2013 and Windows 7. Recently I had to migrate to windows 10 and it seems that now the forms cut them and they are not displayed completely as seen in the attached image. Is there any way for the modSacaleForm module to work properly under windows 10 and office 2013? Thank you very much and greetings.

**Comment by GruberMarkus** [comment]
Sorry for my late answer, I have misconfigured my e-mail notification from GitHub.

Unfortunately, I can only provide modScaleForm as is, as I have not taken care of it since March 2008.

I just downloaded the sample database and tested it on Windows 10 and Office 2016 with all the latest updates, and it is just working fine on different devices, graphic cards and displays:
.) Intel HD 520, 3000x2000, 200% DPI
.) Intel HD 4000, 1600x900, 100% DPI
.) AMD Radeon 6450, 1920x1080, 150% DPI

Could you please try it on another PC?

**Comment by GruberMarkus** [comment]
No feedback from the creator of the issue for a very long time.

**Comment by GruberMarkus** [comment]
No feedback from the creator of the issue for a very long time.
